In [0]:
#Ejercicio 1
#Crea un array 1D que tenga como salida #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#Ejercicio 2
#Extraer del array  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) aquellos valores mayores a 3
res = arr[arr>3]
res

array([4, 5, 6, 7, 8, 9])

In [2]:
#Ejercicio 3
#Extraer del array  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) aquellos valores impares (Pista operacion %)
import numpy as np
arr = np.arange(10)
arr[arr % 2 == 1]
np.where(arr%2==1, 0, arr)

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [0]:
#Ejercicio 4
#Reemplazar del array  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) aquellos valores impares por 0
arr[arr % 2 == 1] =0
arr

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [0]:
#Ejercicio 5
#Conviertel el arrray array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) de 1D a 2D
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
#Ejercicio 6
#Crear un array de dim10 con dimension (2,-1) y otro de dim10 con dimension (2,-1) y concatenalos axis 0 (vertical)
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)
print(np.concatenate([a,b], axis=0))
print(np.vstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [0]:
#Ejercicio 7
#Devuelve los valores en comun entre dos arrays dados
# a = np.array([1,2,3,2,3,4,3,4,5,6])
#b = np.array([7,2,10,2,7,4,9,4,9,8])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [8]:
#Ejercicio 8
#Devuelve los valores diferentes entre dos arrays
#a = np.array([1,2,3,4,5])
#b = np.array([5,6,7,8,9])
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
adiff =np.setdiff1d(a,b)
bdiff =np.setdiff1d(b,a)
res = np.concatenate((adiff, bdiff))
res

array([1, 2, 3, 4, 6, 7, 8, 9])

In [10]:
#Ejercicio 9
#Dados los siguientes arrays:
#a = np.array([1,2,3,2,3,4,3,4,5,6])
#b = np.array([7,2,10,2,7,4,9,4,9,8])
#Devolver las posiciones donde A y B son iguales
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)[0]

array([1, 3, 5, 7])

In [14]:
#Ejercicio 10
# A partir de un array a obtener las posiciones de los valores duplicados
# Array: [0 0 3 0 2 4 2 2 2 2]
# resultado: #> [False  True False  True False False  True  True  True  True]
a = np.array([0,0,3,0,2,4,2,2,2,2])
out = np.full(a.shape[0], True)
print(out)
unique_positions = np.unique(a, return_index=True)
print(unique_positions)
out[unique_positions]= False
out

[ True  True  True  True  True  True  True  True  True  True]
(array([0, 2, 3, 4]), array([0, 4, 2, 5]))


IndexError: ignored