# **INTRO NUMPY**

Numpy es una libreria core para computación científica en Python. Ofrece altas prestaciones para objetos que puedan presentar arrays multidimensionales y herramientas para trabajar con ellos.


Un array es una estructura de datos que puede tener diferentes dimensiones.

*   1D lo denominamos array
*   2D lo denominamos matriz



![texto alternativo](/sample_data/Dibu.jpeg)



## Arrays

En Python un array en un conjunto de valores del mismo tipo que son indexados por un valor entero no negativo.


*   *shape* es una tupla de entero con el tamaño de la matriz en cada dimensión
*   Para importar la librería: > import numpy as np
*   Los indices de los arrays comienzan en 0





In [1]:
import numpy as np
a = np.array([4,5,6])
print(a)
print(type(a))
print(a.shape)
print(a[0])


[4 5 6]
<class 'numpy.ndarray'>
(3,)
4


In [2]:
bnp = np.array([["a","b","c"],["d","e","f"]])
print(bnp.shape)
print(bnp[1,1]) #[fila, columna]
#¿Que ocurre al ejecutar print(bnp[2,1])? 

(2, 3)
e


Python ademas provee de una serie de funciones para crear arrays de una forma mas sencilla, veamos algunas de ellas

*   np.zeros(A) Crea array con dim A y lo inicializa a 0
*   np.ones(A) Crear un array con dim A y lo iniciliza a 1
*   np.full(A, val) Crear un array con dimA y lo inicializa a val
*   np.eye(A) Crear un array con dim A que sea matriz Identidad
*   np.ramdom.ramdom(A) Crear un array con dimA valores ramdoms
*   np.emptylike(x) Crear un array vacio con dim X
*   np.arange(X) Crear un array con valores 0-(X-1)
*   np.intersect1d(a,b) Devuelve un array con valores en comun de a y b
*   np.where(condition(a,b)) Devuelve las posiciones donde se cumple la condicion entre arrays
*   np.concatenate([X, Y], axis=1) Concatena arrays por axis 
*   np.unique(X) Devuelve los valores unicos de una array
*   np.setdiff1d(a,b) Devuelve los valores diferentes entre dos arrays


Mas info mirar el listado de funciones disponibles 

 

In [3]:
zeros = np.zeros((2,2))   
print(zeros)             

ones = np.ones((1,2))    
print(ones)             

full = np.full((2,2), 5)  
print(full)               
                       
eye = np.eye(3)         
print(eye)              

ram = np.random.random((2,2))  
print(ram)                    

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.26847908 0.20275396]
 [0.60432575 0.34759733]]


### Indexando Arrays

Numpy permite diferentes maneras de indexar un array, entre ellas:

*   Slicing 
*   Integer array Indexing
*   Boolena array Indexing
Veamos cada una de ellas

#### Slicing

Supone "extraer un array de otro" o subtraer parte del mismo utlizando los indices
**texto en negrita**

In [4]:
import numpy as np
a = np.random.random((3,4))
print(a)
#Nos quedmos con el subarray 1 y 2 fila, 3 y 4 columna
b = a[:2,2:]
b

[[0.33028062 0.26761393 0.38707409 0.67804225]
 [0.7648155  0.66914846 0.7236008  0.98678945]
 [0.77289417 0.75819896 0.17465499 0.22672948]]


array([[0.38707409, 0.67804225],
       [0.7236008 , 0.98678945]])

#### Integer array indexing

En lugar de modificar el array anterior lo que hacemos es construir uno nuevo a partir de las componentes que nos interesan
*texto en cursiva*

In [0]:
a = np.random.random((3,2))
print(a)
b =  a[[1,1],[0,1]]
print(b)


#### Boolean array indexing

Indexar una matriz de esta forma te permite seleccionar elementos arbitrarios de una matriz. Se suele utilizar para seleccionar los elementos de una matriz que satisfacen una condición




In [0]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
res = (a>2)
print(res)
#Podemos recuperar los valores que lo cumple
print(a[res])
#Otra forma de plantearlo
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Datatypes

Los arrays en numpy son conjuntos de datos del mismo tipo. Numpy provee de un conjunto bastante amplio de tipos de datos que pueden utilizar para contruir arrays, algunos tipos int64, float64, etc... para ver el tipo de un array utilizamos la variable dtype.

In [0]:
import numpy as np
x = np.array([1, 2]) 
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2], dtype=np.int64)
print(x.dtype) 

### Funciones matemáticas sobre arrays

Veamos como podemos aplicar funciones matemáticas sobre nuestros arrays, para algunas podemos hacerlo con operadores matematicos (+,-,..) y con funciones propias


*   Suma: np.add(A,B) o A+B
*   Resta: np.subtract(A,B) o A-B
*   Multiplicación: np.multiply(A,B) o A*B
*   División: np.divide(A,B) o A/B



In [0]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
#suma
print(a + b)
print(np.add(a,b))

#resta
print(a-b)
print(np.subtract(a,b))


#multiplicación 
print(a*b)
print(np.multiply(a,b))

#division
print(a/b)
print(np.divide(a,b))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


#### Operacion internas en los arrays

Podemos hacer operaciones internas con los valores de los arrays como


*   Suma valores array con np.sum(a)
*   Suma de valores por columna en matriz np.sum(a, axis=0)
*   Suma de valores por fila en matriz np.suma(a, axis=1)

Tambien podemos obtener la matriz inversa de una forma muy sencilla aplicando al matriz la funcion .T
 


In [7]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x)) 
print(np.sum(x, axis=0)) 
print(np.sum(x, axis=1))  

#Calculamos la transpuesta de x
x.T

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


array([[1, 3],
       [2, 4]])

### Reshape

Puede ocurrir que necesitemos modificarla forma que tienen nuestros datos y las estructuras que contienen así como tener la posibilidad de operar con matrices de diferentes tamaño.
Para cambiar la forma de un array usamos el np.reshape(X, newDim)




In [8]:
import numpy as np

v = np.arange(8)
print(v)
y = v.reshape(2,4)
print(y)
z = v.reshape(2,2,2)
print(z)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## HOLA
### **asdf**

